title: The Musings of Yefim Vedernikoff
twitter_username: johndoe
github_username: johndoe
email: john@doe.com
baseurl: /bilious_salad
remote_theme: yefim/yefeme
remote_theme_layouts:
  - default
  - post
  - home
